# MindBoom 3.0 - Twilio - Docker Compose Configuration
# Production-ready configuration

version: '3.8'

services:
  app:
    image: mindboom-3.0-twilio:latest
    container_name: mindboom-production
    build:
      context: .
      dockerfile: Dockerfile
      args:
        VITE_SUPABASE_URL: ${VITE_SUPABASE_URL}
        VITE_SUPABASE_ANON_KEY: ${VITE_SUPABASE_ANON_KEY}
        VITE_APP_ENV: ${VITE_APP_ENV:-production}
    ports:
      - "80:80"
      - "443:443"
    environment:
      - NODE_ENV=production
    volumes:
      # Mount custom nginx config if needed
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
      # Mount SSL certificates (uncomment when using HTTPS)
      # - ./ssl/cert.pem:/etc/nginx/ssl/cert.pem:ro
      # - ./ssl/key.pem:/etc/nginx/ssl/key.pem:ro
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/health.json"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 10s
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    labels:
      - "com.mindboom.app=mindboom-3.0-twilio"
      - "com.mindboom.env=production"
      - "com.mindboom.version=3.0.0"
    networks:
      - mindboom-network

  # Uncomment to add watchtower for automatic updates
  # watchtower:
  #   image: containrrr/watchtower
  #   container_name: watchtower
  #   volumes:
  #     - /var/run/docker.sock:/var/run/docker.sock
  #   command: --interval 300 --cleanup
  #   restart: unless-stopped
  #   networks:
  #     - mindboom-network

networks:
  mindboom-network:
    driver: bridge

# Uncomment to add persistent volumes
# volumes:
#   nginx-logs:
#     driver: local
